import { Component } from '@angular/core';
import { IonApp, IonRouterOutlet } from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import {
  eyeOffOutline,
  eyeOutline,
  fingerPrintOutline,
  fingerPrint,
  settingsOutline,
  layersSharp,
  notificationsOutline,
  logoGithub,
  logoLinkedin,
  logoInstagram,
  checkmarkOutline,
  chevronForwardOutline,
  chevronBackOutline,
  eye,
  lockClosed,
  time,
  list,
  calendar,
  business,
  statsChart,
  documentText,
  notifications,
  settings,
  logOut,
  personCircle,
  logOutOutline,
  closeCircle,
  logoAngular,
  logoReact,
  logoVue,
  cloudUpload,
  checkmarkCircle,
  warning,
  close,
  refresh,
  camera,
  images,
  folder,
  image,
  trash,
  help,
  mail,
  personOutline,
  statsChartOutline,
  timeOutline,
  alertCircleOutline,
  funnelOutline,
  ellipsisVerticalOutline,
  ellipsisVertical,
} from 'ionicons/icons';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  imports: [IonApp, IonRouterOutlet],
})
export class AppComponent {
  constructor() {
    addIcons({
      eyeOffOutline,
      eyeOutline,
      fingerPrintOutline,
      fingerPrint,
      settingsOutline,
      layersSharp,
      notificationsOutline,
      logoGithub,
      logoLinkedin,
      logoInstagram,
      checkmarkOutline,
      chevronForwardOutline,
      chevronBackOutline,
      eye,
      lockClosed,
      time,
      list,
      calendar,
      business,
      statsChart,
      documentText,
      notifications,
      settings,
      logOut,
      personCircle,
      logOutOutline,
      closeCircle,
      logoAngular,
      logoReact,
      logoVue,
      cloudUpload,
      checkmarkCircle,
      warning,
      close,
      refresh,
      camera,
      images,
      folder,
      image,
      trash,
      help,
      mail,
      personOutline,
      statsChartOutline,
      timeOutline,
      alertCircleOutline,
      funnelOutline,
      ellipsisVerticalOutline,
      ellipsisVertical,
    });
  }
}
